//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/cstrike/zm_new_cordobez_voa2.html
halflife.wad
xeno.wad
itsitaly.wad
maps/zm_new_cordobez_voa2.bsp
maps/zm_new_cordobez_voa2.txt
