; Maps configuration file
; File location: $moddir/addons/amxmodx/configs/maps.ini
; To use with Maps Menu plugin

zm_ice_attack3
zm_dust2_2x2
zm_aztec_infinity
zm_vendetta
zm_zombust
zm_mario_lg
zm_kill_duster
zm_fox
zm_toxic_house2
zm_deposito_v2
zm_hospital_2
zm_inferno
zm_ugc_ground
zm_ultracity
zm_new_cordobez_voa2
